global GEO "~/investigacion/2016/suicide/data/geography/"
use "$GEO/nchs2fips_county1990.dta", clear
set obs 3133
replace stateoc=9 in 3133
replace countyoc=1 in 3133
replace countyname = "District of Columbia" in 3133
replace statename = "District of Columbia" in 3133
replace fipsst = 11 in 3133
replace fipsco = "11001" in 3133
set obs 3134
replace stateoc=11 in 3134
replace countyoc=1 in 3134
replace countyname = "Appling" in 3134
replace statename = "Georgia" in 3134
replace fipsst = 13 in 3134
replace fipsco = "13001" in 3134

*ALASKA
replace countyoc = 2 if fipsco=="02130"
replace countyoc = 3 if fipsco=="02280"
replace countyoc = 4 if fipsco=="02220"
replace countyoc = 5 if fipsco=="02110"
replace countyoc = 6 if fipsco=="02231"
replace countyoc = 7 if fipsco=="02240"
replace countyoc = 8 if fipsco=="02261"
replace countyoc = 9 if fipsco=="02170"
replace countyoc = 10 if fipsco=="02020"
replace countyoc = 11 if fipsco=="02100"
replace countyoc = 12 if fipsco=="02122"
replace countyoc = 13 if fipsco=="02150"
replace countyoc = 14 if fipsco=="02010"
replace countyoc = 15 if fipsco=="02060"
replace countyoc = 16 if fipsco=="02050"
replace countyoc = 17 if fipsco=="02070"
replace countyoc = 18 if fipsco=="02290"
replace countyoc = 19 if fipsco=="02090"
replace countyoc = 20 if fipsco=="02201"
replace countyoc = 21 if fipsco=="02185"
replace countyoc = 22 if fipsco=="02140"
replace countyoc = 23 if fipsco=="02180"
replace countyoc = 24 if fipsco=="02270"
*check 20(2201) as Upper Yukon/Prince of Wales

replace stateoc = 51 if fipsco=="30113"
replace countyoc = 24 if fipsco=="30113"
replace countyoc = 100 if fipsco == "35006"
replace countyoc = countyoc - 1 if stateoc==32&countyoc>3

*New York
replace countyoc = countyoc + 1 if stateoc==33&countyoc>22
replace countyoc = countyoc + 1 if stateoc==33&countyoc>39
replace countyoc = countyoc + 1 if stateoc==33&countyoc>41

*North Carolina
replace countyoc = countyoc -1 if stateoc==34

*South Dakota
replace countyoc = countyoc + 1 if stateoc==42&countyoc>0
replace countyoc = countyoc + 1 if stateoc==42&countyoc>66

*Virginia
replace countyoc=0 if countyname=="Accomack"&statename=="Virginia"
replace countyoc=1 if countyname=="Albemarle"&statename=="Virginia"
replace countyoc=2 if countyname=="Alleghany"&statename=="Virginia"
replace countyoc=3 if countyname=="Amelia"&statename=="Virginia"
replace countyoc=4 if countyname=="Amherst"&statename=="Virginia"
replace countyoc=5 if countyname=="Appomattox"&statename=="Virginia"
replace countyoc=6 if countyname=="Arlington"&statename=="Virginia"
replace countyoc=7 if countyname=="Augusta"&statename=="Virginia"
replace countyoc=8 if countyname=="Bath"&statename=="Virginia"
replace countyoc=9 if countyname=="Bedford"&statename=="Virginia"
replace countyoc=10 if countyname=="Bland"&statename=="Virginia"
replace countyoc=11 if countyname=="Botetourt"&statename=="Virginia"
replace countyoc=12 if countyname=="Brunswick"&statename=="Virginia"
replace countyoc=13 if countyname=="Buchanan"&statename=="Virginia"
replace countyoc=14 if countyname=="Buckingham"&statename=="Virginia"
replace countyoc=15 if countyname=="Campbell"&statename=="Virginia"
replace countyoc=16 if countyname=="Caroline"&statename=="Virginia"
replace countyoc=17 if countyname=="Carroll"&statename=="Virginia"
replace countyoc=18 if countyname=="Charles City"&statename=="Virginia"
replace countyoc=19 if countyname=="Charlotte"&statename=="Virginia"
replace countyoc=20 if countyname=="Chesterfield"&statename=="Virginia"
replace countyoc=21 if countyname=="Clarke"&statename=="Virginia"
replace countyoc=22 if countyname=="Craig"&statename=="Virginia"
replace countyoc=23 if countyname=="Culpeper"&statename=="Virginia"
replace countyoc=24 if countyname=="Cumberland"&statename=="Virginia"
replace countyoc=25 if countyname=="Dickenson"&statename=="Virginia"
replace countyoc=26 if countyname=="Dinwiddie"&statename=="Virginia"
replace countyoc=28 if countyname=="Essex"&statename=="Virginia"
replace countyoc=29 if countyname=="Fairfax"&statename=="Virginia"
replace countyoc=30 if countyname=="Fauquier"&statename=="Virginia"
replace countyoc=31 if countyname=="Floyd"&statename=="Virginia"
replace countyoc=32 if countyname=="Fluvanna"&statename=="Virginia"
replace countyoc=33 if countyname=="Franklin"&statename=="Virginia"
replace countyoc=34 if countyname=="Frederick"&statename=="Virginia"
replace countyoc=35 if countyname=="Giles"&statename=="Virginia"
replace countyoc=36 if countyname=="Gloucester"&statename=="Virginia"
replace countyoc=37 if countyname=="Goochland"&statename=="Virginia"
replace countyoc=38 if countyname=="Grayson"&statename=="Virginia"
replace countyoc=39 if countyname=="Greene"&statename=="Virginia"
replace countyoc=40 if countyname=="Greensville"&statename=="Virginia"
replace countyoc=41 if countyname=="Halifax"&statename=="Virginia"
replace countyoc=42 if countyname=="Hanover"&statename=="Virginia"
replace countyoc=43 if countyname=="Henrico"&statename=="Virginia"
replace countyoc=44 if countyname=="Henry"&statename=="Virginia"
replace countyoc=45 if countyname=="Highland"&statename=="Virginia"
replace countyoc=46 if countyname=="Isle of Wight"&statename=="Virginia"
replace countyoc=47 if countyname=="James City"&statename=="Virginia"
replace countyoc=48 if countyname=="King and Queen"&statename=="Virginia"
replace countyoc=49 if countyname=="King George"&statename=="Virginia"
replace countyoc=50 if countyname=="King William"&statename=="Virginia"
replace countyoc=51 if countyname=="Lancaster"&statename=="Virginia"
replace countyoc=52 if countyname=="Lee"&statename=="Virginia"
replace countyoc=53 if countyname=="Loudoun"&statename=="Virginia"
replace countyoc=54 if countyname=="Louisa"&statename=="Virginia"
replace countyoc=55 if countyname=="Lunenburg"&statename=="Virginia"
replace countyoc=56 if countyname=="Madison"&statename=="Virginia"
replace countyoc=57 if countyname=="Mathews"&statename=="Virginia"
replace countyoc=58 if countyname=="Mecklenburg"&statename=="Virginia"
replace countyoc=59 if countyname=="Middlesex"&statename=="Virginia"
replace countyoc=60 if countyname=="Montgomery"&statename=="Virginia"
replace countyoc=61 if countyname=="Nansemond"&statename=="Virginia"
replace countyoc=62 if countyname=="Nelson"&statename=="Virginia"
replace countyoc=63 if countyname=="New Kent"&statename=="Virginia"
replace countyoc=64 if countyname=="Norfolk"&statename=="Virginia"
replace countyoc=65 if countyname=="Northampton"&statename=="Virginia"
replace countyoc=66 if countyname=="Northumberland"&statename=="Virginia"
replace countyoc=67 if countyname=="Nottoway"&statename=="Virginia"
replace countyoc=68 if countyname=="Orange"&statename=="Virginia"
replace countyoc=69 if countyname=="Page"&statename=="Virginia"
replace countyoc=70 if countyname=="Patrick"&statename=="Virginia"
replace countyoc=71 if countyname=="Pittsylvania"&statename=="Virginia"
replace countyoc=72 if countyname=="Powhatan"&statename=="Virginia"
replace countyoc=73 if countyname=="Prince Edward"&statename=="Virginia"
replace countyoc=74 if countyname=="Prince George"&statename=="Virginia"
replace countyoc=75 if countyname=="Prince William"&statename=="Virginia"
replace countyoc=77 if countyname=="Pulaski"&statename=="Virginia"
replace countyoc=78 if countyname=="Rappahannock"&statename=="Virginia"
replace countyoc=79 if countyname=="Richmond"&statename=="Virginia"
replace countyoc=80 if countyname=="Roanoke"&statename=="Virginia"
replace countyoc=81 if countyname=="Rockbridge"&statename=="Virginia"
replace countyoc=82 if countyname=="Rockingham"&statename=="Virginia"
replace countyoc=83 if countyname=="Russell"&statename=="Virginia"
replace countyoc=84 if countyname=="Scott"&statename=="Virginia"
replace countyoc=85 if countyname=="Shenandoah"&statename=="Virginia"
replace countyoc=86 if countyname=="Smyth"&statename=="Virginia"
replace countyoc=87 if countyname=="Southampton"&statename=="Virginia"
replace countyoc=88 if countyname=="Spotsylvania"&statename=="Virginia"
replace countyoc=89 if countyname=="Stafford"&statename=="Virginia"
replace countyoc=90 if countyname=="Surry"&statename=="Virginia"
replace countyoc=91 if countyname=="Sussex"&statename=="Virginia"
replace countyoc=92 if countyname=="Tazewell"&statename=="Virginia"
replace countyoc=93 if countyname=="Warren"&statename=="Virginia"
replace countyoc=95 if countyname=="Washington"&statename=="Virginia"
replace countyoc=96 if countyname=="Westmoreland"&statename=="Virginia"
replace countyoc=97 if countyname=="Wise"&statename=="Virginia"
replace countyoc=98 if countyname=="Wythe"&statename=="Virginia"
replace countyoc=99 if countyname=="York"&statename=="Virginia"
replace countyoc=100 if countyname=="Alexandria city"&statename=="Virginia"
replace countyoc=101 if countyname=="Bristol city"&statename=="Virginia"
replace countyoc=102 if countyname=="Buena Vista city"&statename=="Virginia"
replace countyoc=103 if countyname=="Charlottesville city"&statename=="Virginia"
replace countyoc=209 if countyname=="Chesapeake city"&statename=="Virginia"
replace countyoc=104 if countyname=="Clifton Forge city"&statename=="Virginia"
replace countyoc=105 if countyname=="Colonial Heights city"&statename=="Virginia"
replace countyoc=106 if countyname=="Covington city"&statename=="Virginia"
replace countyoc=107 if countyname=="Danville city"&statename=="Virginia"
replace countyoc=208 if countyname=="Fairfax city"&statename=="Virginia"
replace countyoc=108 if countyname=="Falls Church city"&statename=="Virginia"
replace countyoc=207 if countyname=="Franklin city"&statename=="Virginia"
replace countyoc=109 if countyname=="Fredericksburg city"&statename=="Virginia"
replace countyoc=110 if countyname=="Galax city"&statename=="Virginia"
replace countyoc=111 if countyname=="Hampton city"&statename=="Virginia"
replace countyoc=112 if countyname=="Harrisonburg city"&statename=="Virginia"
replace countyoc=113 if countyname=="Hopewell city"&statename=="Virginia"
replace countyoc=114 if countyname=="Lynchburg city"&statename=="Virginia"
replace countyoc=115 if countyname=="Martinsville city"&statename=="Virginia"
replace countyoc=116 if countyname=="Newport News city"&statename=="Virginia"
replace countyoc=117 if countyname=="Norfolk city"&statename=="Virginia"
replace countyoc=118 if countyname=="Norton city"&statename=="Virginia"
replace countyoc=119 if countyname=="Petersburg city"&statename=="Virginia"
replace countyoc=120 if countyname=="Portsmouth city"&statename=="Virginia"
replace countyoc=121 if countyname=="Radford city"&statename=="Virginia"
replace countyoc=122 if countyname=="Richmond city"&statename=="Virginia"
replace countyoc=123 if countyname=="Roanoke city"&statename=="Virginia"
replace countyoc=124 if countyname=="South Boston city"&statename=="Virginia"
replace countyoc=126 if countyname=="Staunton city"&statename=="Virginia"
replace countyoc=127 if countyname=="Suffolk city"&statename=="Virginia"
replace countyoc=128 if countyname=="Virginia Beach city"&statename=="Virginia"
replace countyoc=129 if countyname=="Waynesboro city"&statename=="Virginia"
replace countyoc=130 if countyname=="Williamsburg city"&statename=="Virginia"
replace countyoc=131 if countyname=="Winchester city"&statename=="Virginia"
replace countyoc=200 if countyname=="Bedford city"&statename=="Virginia"
replace countyoc=201 if countyname=="Lexington city"&statename=="Virginia"
replace countyoc=202 if countyname=="Manassas city"&statename=="Virginia"
replace countyoc=203 if countyname=="Salem city"&statename=="Virginia"
replace countyoc=204 if countyname=="Emporia city"&statename=="Virginia"
replace countyoc=205 if countyname=="Manassas Park city"&statename=="Virginia"
replace countyoc=206 if countyname=="Poquoson city"&statename=="Virginia"

replace countyoc = countyoc -1 if stateoc==50&countyoc>39
replace countyoc = 72 if fipsco=="55078"


save "$GEO/nchs2fips_county1959-1961.dta", replace
