global GEO "~/investigacion/2016/suicide/data/geography/"
use "$GEO/nchs2fips_county1990.dta", clear
set obs 3133
replace stateoc=11 in 3133
replace countyoc=1 in 3133
replace countyname = "Appling" in 3133
replace statename = "Georgia" in 3133
replace fipsst = 13 in 3133
replace fipsco = "13001" in 3133
set obs 3134
replace stateoc=9 in 3134
replace countyoc=1 in 3134
replace countyname = "District of Columbia" in 3134
replace statename = "District of Columbia" in 3134
replace fipsst = 11 in 3134
replace fipsco = "11001" in 3134
replace countyoc=66 if fipsco=="46135"
replace countyoc=67 if fipsco=="46137"
replace stateoc=51 if fipsco=="30113"
replace countyoc=24 if fipsco=="30113"
set obs 3135
replace stateoc=42 in 3135
replace countyoc=65 in 3135
replace countyname = "Washabaugh" in 3135
replace statename = "South Dakota" in 3135
replace fipsst = 30 in 3135
replace fipsco = "46135" in 3135
    

replace countyoc=3 if countyname=="Accomack"&statename=="Virginia"
replace countyoc=6 if countyname=="Albemarle"&statename=="Virginia"
replace countyoc=9 if countyname=="Alleghany"&statename=="Virginia"
replace countyoc=12 if countyname=="Amelia"&statename=="Virginia"
replace countyoc=15 if countyname=="Amherst"&statename=="Virginia"
replace countyoc=18 if countyname=="Appomattox"&statename=="Virginia"
replace countyoc=21 if countyname=="Arlington"&statename=="Virginia"
replace countyoc=24 if countyname=="Augusta"&statename=="Virginia"
replace countyoc=27 if countyname=="Bath"&statename=="Virginia"
replace countyoc=30 if countyname=="Bedford"&statename=="Virginia"
replace countyoc=33 if countyname=="Bland"&statename=="Virginia"
replace countyoc=36 if countyname=="Botetourt"&statename=="Virginia"
replace countyoc=39 if countyname=="Brunswick"&statename=="Virginia"
replace countyoc=42 if countyname=="Buchanan"&statename=="Virginia"
replace countyoc=45 if countyname=="Buckingham"&statename=="Virginia"
replace countyoc=48 if countyname=="Campbell"&statename=="Virginia"
replace countyoc=51 if countyname=="Caroline"&statename=="Virginia"
replace countyoc=54 if countyname=="Carroll"&statename=="Virginia"
replace countyoc=57 if countyname=="Charles City"&statename=="Virginia"
replace countyoc=60 if countyname=="Charlotte"&statename=="Virginia"
replace countyoc=63 if countyname=="Chesterfield"&statename=="Virginia"
replace countyoc=66 if countyname=="Clarke"&statename=="Virginia"
replace countyoc=69 if countyname=="Craig"&statename=="Virginia"
replace countyoc=72 if countyname=="Culpeper"&statename=="Virginia"
replace countyoc=75 if countyname=="Cumberland"&statename=="Virginia"
replace countyoc=78 if countyname=="Dickenson"&statename=="Virginia"
replace countyoc=81 if countyname=="Dinwiddie"&statename=="Virginia"
replace countyoc=84 if countyname=="Essex"&statename=="Virginia"
replace countyoc=87 if countyname=="Fairfax"&statename=="Virginia"
replace countyoc=90 if countyname=="Fauquier"&statename=="Virginia"
replace countyoc=93 if countyname=="Floyd"&statename=="Virginia"
replace countyoc=96 if countyname=="Fluvanna"&statename=="Virginia"
replace countyoc=99 if countyname=="Franklin"&statename=="Virginia"
replace countyoc=102 if countyname=="Frederick"&statename=="Virginia"
replace countyoc=105 if countyname=="Giles"&statename=="Virginia"
replace countyoc=108 if countyname=="Gloucester"&statename=="Virginia"
replace countyoc=111 if countyname=="Goochland"&statename=="Virginia"
replace countyoc=114 if countyname=="Grayson"&statename=="Virginia"
replace countyoc=117 if countyname=="Greene"&statename=="Virginia"
replace countyoc=120 if countyname=="Greensville"&statename=="Virginia"
replace countyoc=123 if countyname=="Halifax"&statename=="Virginia"
replace countyoc=126 if countyname=="Hanover"&statename=="Virginia"
replace countyoc=129 if countyname=="Henrico"&statename=="Virginia"
replace countyoc=132 if countyname=="Henry"&statename=="Virginia"
replace countyoc=135 if countyname=="Highland"&statename=="Virginia"
replace countyoc=138 if countyname=="Isle of Wight"&statename=="Virginia"
replace countyoc=141 if countyname=="James City"&statename=="Virginia"
replace countyoc=144 if countyname=="King and Queen"&statename=="Virginia"
replace countyoc=147 if countyname=="King George"&statename=="Virginia"
replace countyoc=150 if countyname=="King William"&statename=="Virginia"
replace countyoc=153 if countyname=="Lancaster"&statename=="Virginia"
replace countyoc=156 if countyname=="Lee"&statename=="Virginia"
replace countyoc=159 if countyname=="Loudoun"&statename=="Virginia"
replace countyoc=162 if countyname=="Louisa"&statename=="Virginia"
replace countyoc=165 if countyname=="Lunenburg"&statename=="Virginia"
replace countyoc=168 if countyname=="Madison"&statename=="Virginia"
replace countyoc=171 if countyname=="Mathews"&statename=="Virginia"
replace countyoc=174 if countyname=="Mecklenburg"&statename=="Virginia"
replace countyoc=177 if countyname=="Middlesex"&statename=="Virginia"
replace countyoc=180 if countyname=="Montgomery"&statename=="Virginia"
replace countyoc=183 if countyname=="Nansemond"&statename=="Virginia"
replace countyoc=186 if countyname=="Nelson"&statename=="Virginia"
replace countyoc=189 if countyname=="New Kent"&statename=="Virginia"
replace countyoc=195 if countyname=="Northampton"&statename=="Virginia"
replace countyoc=198 if countyname=="Northumberland"&statename=="Virginia"
replace countyoc=201 if countyname=="Nottoway"&statename=="Virginia"
replace countyoc=204 if countyname=="Orange"&statename=="Virginia"
replace countyoc=207 if countyname=="Page"&statename=="Virginia"
replace countyoc=210 if countyname=="Patrick"&statename=="Virginia"
replace countyoc=213 if countyname=="Pittsylvania"&statename=="Virginia"
replace countyoc=216 if countyname=="Powhatan"&statename=="Virginia"
replace countyoc=219 if countyname=="Prince Edward"&statename=="Virginia"
replace countyoc=222 if countyname=="Prince George"&statename=="Virginia"
replace countyoc=225 if countyname=="Prince William"&statename=="Virginia"
replace countyoc=231 if countyname=="Pulaski"&statename=="Virginia"
replace countyoc=234 if countyname=="Rappahannock"&statename=="Virginia"
replace countyoc=237 if countyname=="Richmond"&statename=="Virginia"
replace countyoc=240 if countyname=="Roanoke"&statename=="Virginia"
replace countyoc=243 if countyname=="Rockbridge"&statename=="Virginia"
replace countyoc=246 if countyname=="Rockingham"&statename=="Virginia"
replace countyoc=249 if countyname=="Russell"&statename=="Virginia"
replace countyoc=252 if countyname=="Scott"&statename=="Virginia"
replace countyoc=255 if countyname=="Shenandoah"&statename=="Virginia"
replace countyoc=258 if countyname=="Smyth"&statename=="Virginia"
replace countyoc=261 if countyname=="Southampton"&statename=="Virginia"
replace countyoc=264 if countyname=="Spotsylvania"&statename=="Virginia"
replace countyoc=267 if countyname=="Stafford"&statename=="Virginia"
replace countyoc=270 if countyname=="Surry"&statename=="Virginia"
replace countyoc=273 if countyname=="Sussex"&statename=="Virginia"
replace countyoc=276 if countyname=="Tazewell"&statename=="Virginia"
replace countyoc=279 if countyname=="Warren"&statename=="Virginia"
replace countyoc=282 if countyname=="Washington"&statename=="Virginia"
replace countyoc=285 if countyname=="Westmoreland"&statename=="Virginia"
replace countyoc=288 if countyname=="Wise"&statename=="Virginia"
replace countyoc=291 if countyname=="Wythe"&statename=="Virginia"
replace countyoc=294 if countyname=="York"&statename=="Virginia"
replace countyoc=297 if countyname=="Alexandria city"&statename=="Virginia"
replace countyoc=300 if countyname=="Bristol city"&statename=="Virginia"
replace countyoc=303 if countyname=="Buena Vista city"&statename=="Virginia"
replace countyoc=306 if countyname=="Charlottesville city"&statename=="Virginia"
replace countyoc=307 if countyname=="Chesapeake city"&statename=="Virginia"
replace countyoc=309 if countyname=="Clifton Forge city"&statename=="Virginia"
replace countyoc=312 if countyname=="Colonial Heights city"&statename=="Virginia"
replace countyoc=315 if countyname=="Covington city"&statename=="Virginia"
replace countyoc=318 if countyname=="Danville city"&statename=="Virginia"
replace countyoc=321 if countyname=="Fairfax city"&statename=="Virginia"
replace countyoc=324 if countyname=="Falls Church city"&statename=="Virginia"
replace countyoc=327 if countyname=="Franklin city"&statename=="Virginia"
replace countyoc=330 if countyname=="Fredericksburg city"&statename=="Virginia"
replace countyoc=333 if countyname=="Galax city"&statename=="Virginia"
replace countyoc=336 if countyname=="Hampton city"&statename=="Virginia"
replace countyoc=339 if countyname=="Harrisonburg city"&statename=="Virginia"
replace countyoc=342 if countyname=="Hopewell city"&statename=="Virginia"
replace countyoc=345 if countyname=="Lynchburg city"&statename=="Virginia"
replace countyoc=348 if countyname=="Martinsville city"&statename=="Virginia"
replace countyoc=351 if countyname=="Newport News city"&statename=="Virginia"
replace countyoc=354 if countyname=="Norfolk city"&statename=="Virginia"
replace countyoc=357 if countyname=="Norton city"&statename=="Virginia"
replace countyoc=360 if countyname=="Petersburg city"&statename=="Virginia"
replace countyoc=363 if countyname=="Portsmouth city"&statename=="Virginia"
replace countyoc=366 if countyname=="Radford city"&statename=="Virginia"
replace countyoc=369 if countyname=="Richmond city"&statename=="Virginia"
replace countyoc=372 if countyname=="Roanoke city"&statename=="Virginia"
replace countyoc=375 if countyname=="South Boston city"&statename=="Virginia"
replace countyoc=381 if countyname=="Staunton city"&statename=="Virginia"
replace countyoc=384 if countyname=="Suffolk city"&statename=="Virginia"
replace countyoc=387 if countyname=="Virginia Beach city"&statename=="Virginia"
replace countyoc=390 if countyname=="Waynesboro city"&statename=="Virginia"
replace countyoc=393 if countyname=="Williamsburg city"&statename=="Virginia"
replace countyoc=396 if countyname=="Winchester city"&statename=="Virginia"
replace countyoc=401 if countyname=="Bedford city"&statename=="Virginia"
replace countyoc=402 if countyname=="Lexington city"&statename=="Virginia"
replace countyoc=403 if countyname=="Manassas city"&statename=="Virginia"
replace countyoc=404 if countyname=="Salem city"&statename=="Virginia"
replace countyoc=405 if countyname=="Emporia city"&statename=="Virginia"
replace countyoc=406 if countyname=="Manassas Park city"&statename=="Virginia"
replace countyoc=407 if countyname=="Poquoson city"&statename=="Virginia"

save "$GEO/nchs2fips_county1962-1967.dta", replace
